//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 08:31:12 PM CET 
//


package generatedJAXB;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAnyElement;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for insertionType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="insertionType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="level" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="forwardLooking" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="memory" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="considerFixedCosts" minOccurs="0">
 *           &lt;complexType>
 *             &lt;simpleContent>
 *               &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
 *                 &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}double" />
 *               &lt;/extension>
 *             &lt;/simpleContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="allowVehicleSwitch" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="experimental" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;any minOccurs="0"/>
 *                 &lt;/sequence>
 *                 &lt;attribute name="timeSlice" type="{http://www.w3.org/2001/XMLSchema}string" />
 *                 &lt;attribute name="neighboringSlices" type="{http://www.w3.org/2001/XMLSchema}string" />
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *       &lt;attribute name="name" use="required" type="{http://www.w3schools.com}insertionTypeEnum" />
 *       &lt;attribute name="id" type="{http://www.w3.org/2001/XMLSchema}string" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "insertionType", propOrder = {

})
public class InsertionType {

    protected InsertionType.Level level;
    protected InsertionType.ConsiderFixedCosts considerFixedCosts;
    protected Boolean allowVehicleSwitch;
    protected InsertionType.Experimental experimental;
    @XmlAttribute(name = "name", required = true)
    protected InsertionTypeEnum name;
    @XmlAttribute(name = "id")
    protected String id;

    /**
     * Gets the value of the level property.
     * 
     * @return
     *     possible object is
     *     {@link InsertionType.Level }
     *     
     */
    public InsertionType.Level getLevel() {
        return level;
    }

    /**
     * Sets the value of the level property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsertionType.Level }
     *     
     */
    public void setLevel(InsertionType.Level value) {
        this.level = value;
    }

    /**
     * Gets the value of the considerFixedCosts property.
     * 
     * @return
     *     possible object is
     *     {@link InsertionType.ConsiderFixedCosts }
     *     
     */
    public InsertionType.ConsiderFixedCosts getConsiderFixedCosts() {
        return considerFixedCosts;
    }

    /**
     * Sets the value of the considerFixedCosts property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsertionType.ConsiderFixedCosts }
     *     
     */
    public void setConsiderFixedCosts(InsertionType.ConsiderFixedCosts value) {
        this.considerFixedCosts = value;
    }

    /**
     * Gets the value of the allowVehicleSwitch property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isAllowVehicleSwitch() {
        return allowVehicleSwitch;
    }

    /**
     * Sets the value of the allowVehicleSwitch property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setAllowVehicleSwitch(Boolean value) {
        this.allowVehicleSwitch = value;
    }

    /**
     * Gets the value of the experimental property.
     * 
     * @return
     *     possible object is
     *     {@link InsertionType.Experimental }
     *     
     */
    public InsertionType.Experimental getExperimental() {
        return experimental;
    }

    /**
     * Sets the value of the experimental property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsertionType.Experimental }
     *     
     */
    public void setExperimental(InsertionType.Experimental value) {
        this.experimental = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link InsertionTypeEnum }
     *     
     */
    public InsertionTypeEnum getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsertionTypeEnum }
     *     
     */
    public void setName(InsertionTypeEnum value) {
        this.name = value;
    }

    /**
     * Gets the value of the id property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setId(String value) {
        this.id = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="weight" type="{http://www.w3.org/2001/XMLSchema}double" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class ConsiderFixedCosts {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "weight")
        protected Double weight;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the weight property.
         * 
         * @return
         *     possible object is
         *     {@link Double }
         *     
         */
        public Double getWeight() {
            return weight;
        }

        /**
         * Sets the value of the weight property.
         * 
         * @param value
         *     allowed object is
         *     {@link Double }
         *     
         */
        public void setWeight(Double value) {
            this.weight = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;any minOccurs="0"/>
     *       &lt;/sequence>
     *       &lt;attribute name="timeSlice" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="neighboringSlices" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "any"
    })
    public static class Experimental {

        @XmlAnyElement(lax = true)
        protected Object any;
        @XmlAttribute(name = "timeSlice")
        protected String timeSlice;
        @XmlAttribute(name = "neighboringSlices")
        protected String neighboringSlices;

        /**
         * Gets the value of the any property.
         * 
         * @return
         *     possible object is
         *     {@link Object }
         *     
         */
        public Object getAny() {
            return any;
        }

        /**
         * Sets the value of the any property.
         * 
         * @param value
         *     allowed object is
         *     {@link Object }
         *     
         */
        public void setAny(Object value) {
            this.any = value;
        }

        /**
         * Gets the value of the timeSlice property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getTimeSlice() {
            return timeSlice;
        }

        /**
         * Sets the value of the timeSlice property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setTimeSlice(String value) {
            this.timeSlice = value;
        }

        /**
         * Gets the value of the neighboringSlices property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getNeighboringSlices() {
            return neighboringSlices;
        }

        /**
         * Sets the value of the neighboringSlices property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setNeighboringSlices(String value) {
            this.neighboringSlices = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;simpleContent>
     *     &lt;extension base="&lt;http://www.w3.org/2001/XMLSchema>string">
     *       &lt;attribute name="forwardLooking" type="{http://www.w3.org/2001/XMLSchema}string" />
     *       &lt;attribute name="memory" type="{http://www.w3.org/2001/XMLSchema}string" />
     *     &lt;/extension>
     *   &lt;/simpleContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "value"
    })
    public static class Level {

        @XmlValue
        protected String value;
        @XmlAttribute(name = "forwardLooking")
        protected String forwardLooking;
        @XmlAttribute(name = "memory")
        protected String memory;

        /**
         * Gets the value of the value property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getValue() {
            return value;
        }

        /**
         * Sets the value of the value property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setValue(String value) {
            this.value = value;
        }

        /**
         * Gets the value of the forwardLooking property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getForwardLooking() {
            return forwardLooking;
        }

        /**
         * Sets the value of the forwardLooking property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setForwardLooking(String value) {
            this.forwardLooking = value;
        }

        /**
         * Gets the value of the memory property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getMemory() {
            return memory;
        }

        /**
         * Sets the value of the memory property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setMemory(String value) {
            this.memory = value;
        }

    }

}
