//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 08:31:12 PM CET 
//


package generatedJAXB;

import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="iterations" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *           &lt;element name="maxIterations" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;/choice>
 *         &lt;choice>
 *           &lt;element name="prematureBreak" type="{http://www.w3schools.com}prematureBreakType" minOccurs="0"/>
 *           &lt;element name="terminationCriteria">
 *             &lt;complexType>
 *               &lt;complexContent>
 *                 &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                   &lt;sequence>
 *                     &lt;element name="termination" type="{http://www.w3schools.com}prematureBreakType" maxOccurs="unbounded" minOccurs="0"/>
 *                   &lt;/sequence>
 *                 &lt;/restriction>
 *               &lt;/complexContent>
 *             &lt;/complexType>
 *           &lt;/element>
 *         &lt;/choice>
 *         &lt;element name="construction" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="insertion" type="{http://www.w3schools.com}insertionType"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="strategy">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="memory" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *                   &lt;element name="searchStrategies">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="searchStrategy" type="{http://www.w3schools.com}searchStrategyType" maxOccurs="unbounded"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "iterations",
    "maxIterations",
    "prematureBreak",
    "terminationCriteria",
    "construction",
    "strategy"
})
@XmlRootElement(name = "algorithm")
public class Algorithm {

    protected BigInteger iterations;
    protected BigInteger maxIterations;
    protected PrematureBreakType prematureBreak;
    protected Algorithm.TerminationCriteria terminationCriteria;
    protected Algorithm.Construction construction;
    @XmlElement(required = true)
    protected Algorithm.Strategy strategy;

    /**
     * Gets the value of the iterations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIterations() {
        return iterations;
    }

    /**
     * Sets the value of the iterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIterations(BigInteger value) {
        this.iterations = value;
    }

    /**
     * Gets the value of the maxIterations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxIterations() {
        return maxIterations;
    }

    /**
     * Sets the value of the maxIterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxIterations(BigInteger value) {
        this.maxIterations = value;
    }

    /**
     * Gets the value of the prematureBreak property.
     * 
     * @return
     *     possible object is
     *     {@link PrematureBreakType }
     *     
     */
    public PrematureBreakType getPrematureBreak() {
        return prematureBreak;
    }

    /**
     * Sets the value of the prematureBreak property.
     * 
     * @param value
     *     allowed object is
     *     {@link PrematureBreakType }
     *     
     */
    public void setPrematureBreak(PrematureBreakType value) {
        this.prematureBreak = value;
    }

    /**
     * Gets the value of the terminationCriteria property.
     * 
     * @return
     *     possible object is
     *     {@link Algorithm.TerminationCriteria }
     *     
     */
    public Algorithm.TerminationCriteria getTerminationCriteria() {
        return terminationCriteria;
    }

    /**
     * Sets the value of the terminationCriteria property.
     * 
     * @param value
     *     allowed object is
     *     {@link Algorithm.TerminationCriteria }
     *     
     */
    public void setTerminationCriteria(Algorithm.TerminationCriteria value) {
        this.terminationCriteria = value;
    }

    /**
     * Gets the value of the construction property.
     * 
     * @return
     *     possible object is
     *     {@link Algorithm.Construction }
     *     
     */
    public Algorithm.Construction getConstruction() {
        return construction;
    }

    /**
     * Sets the value of the construction property.
     * 
     * @param value
     *     allowed object is
     *     {@link Algorithm.Construction }
     *     
     */
    public void setConstruction(Algorithm.Construction value) {
        this.construction = value;
    }

    /**
     * Gets the value of the strategy property.
     * 
     * @return
     *     possible object is
     *     {@link Algorithm.Strategy }
     *     
     */
    public Algorithm.Strategy getStrategy() {
        return strategy;
    }

    /**
     * Sets the value of the strategy property.
     * 
     * @param value
     *     allowed object is
     *     {@link Algorithm.Strategy }
     *     
     */
    public void setStrategy(Algorithm.Strategy value) {
        this.strategy = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="insertion" type="{http://www.w3schools.com}insertionType"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "insertion"
    })
    public static class Construction {

        @XmlElement(required = true)
        protected InsertionType insertion;

        /**
         * Gets the value of the insertion property.
         * 
         * @return
         *     possible object is
         *     {@link InsertionType }
         *     
         */
        public InsertionType getInsertion() {
            return insertion;
        }

        /**
         * Sets the value of the insertion property.
         * 
         * @param value
         *     allowed object is
         *     {@link InsertionType }
         *     
         */
        public void setInsertion(InsertionType value) {
            this.insertion = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="memory" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
     *         &lt;element name="searchStrategies">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="searchStrategy" type="{http://www.w3schools.com}searchStrategyType" maxOccurs="unbounded"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "memory",
        "searchStrategies"
    })
    public static class Strategy {

        @XmlElement(defaultValue = "1")
        protected BigInteger memory;
        @XmlElement(required = true)
        protected Algorithm.Strategy.SearchStrategies searchStrategies;

        /**
         * Gets the value of the memory property.
         * 
         * @return
         *     possible object is
         *     {@link BigInteger }
         *     
         */
        public BigInteger getMemory() {
            return memory;
        }

        /**
         * Sets the value of the memory property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigInteger }
         *     
         */
        public void setMemory(BigInteger value) {
            this.memory = value;
        }

        /**
         * Gets the value of the searchStrategies property.
         * 
         * @return
         *     possible object is
         *     {@link Algorithm.Strategy.SearchStrategies }
         *     
         */
        public Algorithm.Strategy.SearchStrategies getSearchStrategies() {
            return searchStrategies;
        }

        /**
         * Sets the value of the searchStrategies property.
         * 
         * @param value
         *     allowed object is
         *     {@link Algorithm.Strategy.SearchStrategies }
         *     
         */
        public void setSearchStrategies(Algorithm.Strategy.SearchStrategies value) {
            this.searchStrategies = value;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType>
         *   &lt;complexContent>
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
         *       &lt;sequence>
         *         &lt;element name="searchStrategy" type="{http://www.w3schools.com}searchStrategyType" maxOccurs="unbounded"/>
         *       &lt;/sequence>
         *     &lt;/restriction>
         *   &lt;/complexContent>
         * &lt;/complexType>
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "searchStrategy"
        })
        public static class SearchStrategies {

            @XmlElement(required = true)
            protected List<SearchStrategyType> searchStrategy;

            /**
             * Gets the value of the searchStrategy property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the JAXB object.
             * This is why there is not a <CODE>set</CODE> method for the searchStrategy property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getSearchStrategy().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link SearchStrategyType }
             * 
             * 
             */
            public List<SearchStrategyType> getSearchStrategy() {
                if (searchStrategy == null) {
                    searchStrategy = new ArrayList<SearchStrategyType>();
                }
                return this.searchStrategy;
            }

        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="termination" type="{http://www.w3schools.com}prematureBreakType" maxOccurs="unbounded" minOccurs="0"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "termination"
    })
    public static class TerminationCriteria {

        protected List<PrematureBreakType> termination;

        /**
         * Gets the value of the termination property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the termination property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getTermination().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link PrematureBreakType }
         * 
         * 
         */
        public List<PrematureBreakType> getTermination() {
            if (termination == null) {
                termination = new ArrayList<PrematureBreakType>();
            }
            return this.termination;
        }

    }

}
