//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 08:31:12 PM CET 
//


package generatedJAXB;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for GendreauGroupType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="GendreauGroupType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="iterations" type="{http://www.w3.org/2001/XMLSchema}integer"/>
 *         &lt;element name="share" type="{http://www.w3.org/2001/XMLSchema}double"/>
 *         &lt;element name="ruin" type="{http://www.w3schools.com}ruinType"/>
 *         &lt;element name="insertion" type="{http://www.w3schools.com}insertionType"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "GendreauGroupType", propOrder = {
    "iterations",
    "share",
    "ruin",
    "insertion"
})
public class GendreauGroupType {

    @XmlElement(required = true)
    protected BigInteger iterations;
    protected double share;
    @XmlElement(required = true)
    protected RuinType ruin;
    @XmlElement(required = true)
    protected InsertionType insertion;

    /**
     * Gets the value of the iterations property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getIterations() {
        return iterations;
    }

    /**
     * Sets the value of the iterations property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setIterations(BigInteger value) {
        this.iterations = value;
    }

    /**
     * Gets the value of the share property.
     * 
     */
    public double getShare() {
        return share;
    }

    /**
     * Sets the value of the share property.
     * 
     */
    public void setShare(double value) {
        this.share = value;
    }

    /**
     * Gets the value of the ruin property.
     * 
     * @return
     *     possible object is
     *     {@link RuinType }
     *     
     */
    public RuinType getRuin() {
        return ruin;
    }

    /**
     * Sets the value of the ruin property.
     * 
     * @param value
     *     allowed object is
     *     {@link RuinType }
     *     
     */
    public void setRuin(RuinType value) {
        this.ruin = value;
    }

    /**
     * Gets the value of the insertion property.
     * 
     * @return
     *     possible object is
     *     {@link InsertionType }
     *     
     */
    public InsertionType getInsertion() {
        return insertion;
    }

    /**
     * Sets the value of the insertion property.
     * 
     * @param value
     *     allowed object is
     *     {@link InsertionType }
     *     
     */
    public void setInsertion(InsertionType value) {
        this.insertion = value;
    }

}
