//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 08:31:12 PM CET 
//


package generatedJAXB;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for insertionTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="insertionTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="bestInsertion"/>
 *     &lt;enumeration value="regretInsertion"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "insertionTypeEnum")
@XmlEnum
public enum InsertionTypeEnum {

    @XmlEnumValue("bestInsertion")
    BEST_INSERTION("bestInsertion"),
    @XmlEnumValue("regretInsertion")
    REGRET_INSERTION("regretInsertion");
    private final String value;

    InsertionTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static InsertionTypeEnum fromValue(String v) {
        for (InsertionTypeEnum c: InsertionTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
