//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 08:31:12 PM CET 
//


package generatedJAXB;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for moduleTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="moduleTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="ruin_and_recreate"/>
 *     &lt;enumeration value="gendreau"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "moduleTypeEnum")
@XmlEnum
public enum ModuleTypeEnum {

    @XmlEnumValue("ruin_and_recreate")
    RUIN_AND_RECREATE("ruin_and_recreate"),
    @XmlEnumValue("gendreau")
    GENDREAU("gendreau");
    private final String value;

    ModuleTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static ModuleTypeEnum fromValue(String v) {
        for (ModuleTypeEnum c: ModuleTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
