//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 08:31:12 PM CET 
//


package generatedJAXB;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the generatedJAXB package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: generatedJAXB
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link Algorithm }
     * 
     */
    public Algorithm createAlgorithm() {
        return new Algorithm();
    }

    /**
     * Create an instance of {@link InsertionType }
     * 
     */
    public InsertionType createInsertionType() {
        return new InsertionType();
    }

    /**
     * Create an instance of {@link SearchStrategyType }
     * 
     */
    public SearchStrategyType createSearchStrategyType() {
        return new SearchStrategyType();
    }

    /**
     * Create an instance of {@link Algorithm.Strategy }
     * 
     */
    public Algorithm.Strategy createAlgorithmStrategy() {
        return new Algorithm.Strategy();
    }

    /**
     * Create an instance of {@link PrematureBreakType }
     * 
     */
    public PrematureBreakType createPrematureBreakType() {
        return new PrematureBreakType();
    }

    /**
     * Create an instance of {@link Algorithm.TerminationCriteria }
     * 
     */
    public Algorithm.TerminationCriteria createAlgorithmTerminationCriteria() {
        return new Algorithm.TerminationCriteria();
    }

    /**
     * Create an instance of {@link Algorithm.Construction }
     * 
     */
    public Algorithm.Construction createAlgorithmConstruction() {
        return new Algorithm.Construction();
    }

    /**
     * Create an instance of {@link PrematureBreakIterationTypeGroup }
     * 
     */
    public PrematureBreakIterationTypeGroup createPrematureBreakIterationTypeGroup() {
        return new PrematureBreakIterationTypeGroup();
    }

    /**
     * Create an instance of {@link ModuleType }
     * 
     */
    public ModuleType createModuleType() {
        return new ModuleType();
    }

    /**
     * Create an instance of {@link SelectorType }
     * 
     */
    public SelectorType createSelectorType() {
        return new SelectorType();
    }

    /**
     * Create an instance of {@link RuinType }
     * 
     */
    public RuinType createRuinType() {
        return new RuinType();
    }

    /**
     * Create an instance of {@link AcceptorType }
     * 
     */
    public AcceptorType createAcceptorType() {
        return new AcceptorType();
    }

    /**
     * Create an instance of {@link GendreauGroupType }
     * 
     */
    public GendreauGroupType createGendreauGroupType() {
        return new GendreauGroupType();
    }

    /**
     * Create an instance of {@link PrematureBreakTimeTypeGroup }
     * 
     */
    public PrematureBreakTimeTypeGroup createPrematureBreakTimeTypeGroup() {
        return new PrematureBreakTimeTypeGroup();
    }

    /**
     * Create an instance of {@link PrematureBreakVariationCoefficientTypeGroup }
     * 
     */
    public PrematureBreakVariationCoefficientTypeGroup createPrematureBreakVariationCoefficientTypeGroup() {
        return new PrematureBreakVariationCoefficientTypeGroup();
    }

    /**
     * Create an instance of {@link RuinAndRecreateGroupType }
     * 
     */
    public RuinAndRecreateGroupType createRuinAndRecreateGroupType() {
        return new RuinAndRecreateGroupType();
    }

    /**
     * Create an instance of {@link InsertionType.Level }
     * 
     */
    public InsertionType.Level createInsertionTypeLevel() {
        return new InsertionType.Level();
    }

    /**
     * Create an instance of {@link InsertionType.ConsiderFixedCosts }
     * 
     */
    public InsertionType.ConsiderFixedCosts createInsertionTypeConsiderFixedCosts() {
        return new InsertionType.ConsiderFixedCosts();
    }

    /**
     * Create an instance of {@link InsertionType.Experimental }
     * 
     */
    public InsertionType.Experimental createInsertionTypeExperimental() {
        return new InsertionType.Experimental();
    }

    /**
     * Create an instance of {@link SearchStrategyType.Modules }
     * 
     */
    public SearchStrategyType.Modules createSearchStrategyTypeModules() {
        return new SearchStrategyType.Modules();
    }

    /**
     * Create an instance of {@link Algorithm.Strategy.SearchStrategies }
     * 
     */
    public Algorithm.Strategy.SearchStrategies createAlgorithmStrategySearchStrategies() {
        return new Algorithm.Strategy.SearchStrategies();
    }

}
