//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.11.21 at 08:31:12 PM CET 
//


package generatedJAXB;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ruinTypeEnum.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="ruinTypeEnum">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="randomRuin"/>
 *     &lt;enumeration value="radialRuin"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "ruinTypeEnum")
@XmlEnum
public enum RuinTypeEnum {

    @XmlEnumValue("randomRuin")
    RANDOM_RUIN("randomRuin"),
    @XmlEnumValue("radialRuin")
    RADIAL_RUIN("radialRuin");
    private final String value;

    RuinTypeEnum(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static RuinTypeEnum fromValue(String v) {
        for (RuinTypeEnum c: RuinTypeEnum.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
